spring:
  application:
    name: maple-user-auth-service
  jmx:
    enabled: false
  mvc:
    enabled: false
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    config:
      enabled: false
  flyway:
    baseline-on-migrate: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    jwt:
      expire-time-in-millis: 86400000
      secret-key: somesecretkeyformapleprojectsomesecretkeyformapleproject

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 860
  error:
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://maple-zipkin-service.maple-tracing.svc.cluster.local:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

http:
  client:
    max-connect-route: 2
    max-connect: 8
    connect-request-timeout: 5000
    connect-timeout: 5000
    socket-timeout: 15000
