version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build JAR
          command: ./gradlew clean build
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/maple-user-auth-service:$CIRCLE_SHA1 -t $DOCKERHUB_USERNAME/maple-user-auth-service:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKERHUB_USERNAME/maple-user-auth-service:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/maple-user-auth-service:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
            - shared-credentials  # Reference your context here
          filters:
            branches:
              only: master
