apiVersion: v1
kind: Service
metadata:
  name: maple-user-auth-postgres-service
  namespace: maple-system
spec:
  type: ClusterIP
  ports:
    - port: 5401
      targetPort: 5432
  selector:
    app: maple-user-auth-postgres
